//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsuptionModelDaily
    {
        public Nullable<double> Amount { get; set; }
        public int MeasurementTime { get; set; }
        public long IDDate { get; set; }
        public int IDDistrict { get; set; }
        public int source { get; set; }
        public string Type { get; set; }
    }
}
