//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consuption
    {
        public long IDConsuption { get; set; }
        public float Amount { get; set; }
        public int DayOffset { get; set; }
        public int MeasurementSequence { get; set; }
        public int MeasurementTime { get; set; }
        public long IDDate { get; set; }
        public long IDConsuptionPlace { get; set; }
        public Nullable<int> source { get; set; }
    
        public virtual ConsuptionPlace ConsuptionPlace { get; set; }
    }
}
