//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAnalytics.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class ConsuptionPlace
    {
        public ConsuptionPlace()
        {
            this.Consuptions = new HashSet<Consuption>();
        }
		[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public long IDConsuptionPlace { get; set; }
        public string ZipCode { get; set; }
    
        public virtual ICollection<Consuption> Consuptions { get; set; }
    }
}
