//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int IDEvents { get; set; }
        public long IDDate { get; set; }
        public string eventName { get; set; }
        public string weekday { get; set; }
        public string eventType { get; set; }
        public System.DateTime eventDate { get; set; }
    }
}
