//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weather
    {
        public string dt { get; set; }
        public Nullable<short> atmosphericPressure { get; set; }
        public Nullable<short> rainfall { get; set; }
        public Nullable<float> windSpeed { get; set; }
        public Nullable<float> windDirection { get; set; }
        public Nullable<float> surfaceTemperature { get; set; }
        public Nullable<float> relativeHumidity { get; set; }
        public Nullable<short> solarFlux { get; set; }
        public Nullable<float> battery { get; set; }
        public Nullable<System.DateTime> dtt { get; set; }
        public long idweather { get; set; }
    }
}
