//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAnalytics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeathersDaily
    {
        public long IDDate { get; set; }
        public Nullable<int> atmosphericPressure { get; set; }
        public Nullable<int> rainfall { get; set; }
        public Nullable<int> windSpeed { get; set; }
        public Nullable<int> surfaceTemperature { get; set; }
        public Nullable<int> solarShine { get; set; }
        public Nullable<int> relativeHumidity { get; set; }
        public int IDLocation { get; set; }
        public string locationName { get; set; }
        public int MeasurementTime { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public int IDweather { get; set; }
    }
}
